# Generated by Django 4.2.7 on 2023-12-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_unique_together_delete_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='first',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='last',
            new_name='last_name',
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('first_name', 'last_name')},
        ),
    ]
